In [0]:
import torch

In [0]:
#Number
t1 = torch.tensor(4.)

In [3]:
t1.shape

torch.Size([])

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t2.shape

torch.Size([4])

In [7]:
t2.dtype

torch.float32

In [8]:
# Matrix
t3 = torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [9]:
t3.shape

torch.Size([3, 2])

In [10]:
# 3D Array
t4 = torch.tensor([
                   [[11,12,13],
                    [13,14,15]],
                   [[15,16,17],
                    [17,18,19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [11]:
t4.shape

torch.Size([2, 2, 3])

In [12]:
t4.ndim

3

## Tesnor Operations and Gradients

In [0]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)

In [14]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

- Pytorch is special because it can automatically compute the derivative of y w.r.t. to the tensors that have __required_grad__ set to __True__. To compute the derivatives we can call __.backward__ method on our result __y__.

In [0]:
y.backward()

In [0]:
x.grad #We have not set requires_grad to True #dy/dx

In [17]:
w.grad # dy/dw

tensor(3.)

In [18]:
b.grad # dy/db

tensor(1.)

## Interation with NUMPY

In [0]:
import numpy as np

In [20]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [21]:
x.dtype

dtype('int64')

In [22]:
y = torch.tensor(x)
y

tensor([[1, 2],
        [3, 4]])

In [23]:
y.dtype

torch.int64

In [24]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [25]:
z.dtype

dtype('int64')